listen = *
protocols = imap lmtp
mail_location = maildir:/mail/Maildir
base_dir = /tmp/dovecot
ssl = required
ssl_cert = </certs/live/@FQDN@/fullchain.pem
ssl_key = </certs/live/@FQDN@/privkey.pem
!include conf.d/*.conf
# Hinweis: Dieses File wird zur Laufzeit auf den FQDN aus .env angepasst.
