listen = *
protocols = imap lmtp
mail_location = maildir:/mail/Maildir
ssl = required
ssl_cert = </certs/live/${FQDN}/fullchain.pem
ssl_key = </certs/live/${FQDN}/privkey.pem
!include conf.d/*.conf
# Hinweis: Falls die Umgebungsvariable FQDN nicht ausgelesen wird, den Hostnamen direkt eintragen.
